declare const _default: {
    Calendar: any;
    Clone: any;
    Code: any;
    Edit: any;
    Filter: any;
    Help: any;
    Ignored: any;
    List: any;
    Maximize: any;
    More: any;
    Note: any;
    Notification: any;
    Pause: any;
    Play: any;
    Plus: any;
    Refresh: any;
    Rerun: any;
    Rollback: any;
    Rotate: any;
    Scope: any;
    Search: any;
    Setup: any;
    Star: any;
    Team: any;
    Trash: any;
    User: any;
    View: any;
    Yaml: any;
};
export default _default;
