apiVersion: v1
kind: Pod
metadata:
  generateName: uikit-
  labels:
    jenkins: uikit
    uikit: uikit
  namespace: jenkins
spec:
  nodeSelector:
    purpose: 'ui-medium'
  containers:
    - name: uikit
      image: us.gcr.io/platform-205701/uikit
      resources:
        requests:
          memory: 4Gi
          cpu: 1
      volumeMounts:
        - mountPath: /jenkins-storage
          name: volume-0
        - mountPath: /var/run/secrets/kubernetes.io/uikit-harness-io-tls
          name: uikit-harness-io-tls
          readOnly: true
      command: ['bash']
      args:
        [
          '/jenkins-storage/ui/uikit/v$VERSION/scripts/docs-runner.sh',
          '/jenkins-storage/ui/uikit/v$VERSION',
          '$GITHUB_HARNESS_BOT_TOKEN'
        ]
  volumes:
    - name: volume-0
      persistentVolumeClaim:
        claimName: nfs
    - name: uikit-harness-io-tls
      secret:
        defaultMode: 420
        secretName: uikit-harness-io-tls
  restartPolicy: Never
