/*
 * Copyright 2024 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 */

export enum ScanToolName {
  anchore = 'Anchore',
  'app-scan' = 'IBM App Scan',
  'aqua-security' = 'Aqua Security',
  'aqua-trivy' = 'Aqua Trivy',
  'aws-ecr' = 'AWS ECR Scan',
  'aws-security-hub' = 'AWS Security Hub',
  bandit = 'Bandit',
  blackduckhub = 'Black Duck Hub',
  brakeman = 'Brakeman',
  burp = 'Burp Suite Enterprise Edition',
  checkmarx = 'Checkmarx',
  codeql = 'CodeQL',
  coverity = 'Coverity',
  custom = 'Custom',
  'data-theorem' = 'Data Theorem',
  'docker-content-trust' = 'Docker Content Trust',
  'docker-image-scan' = 'Docker Clair',
  external = 'Custom Scan Tool',
  fortify = 'Fortify',
  fortifyondemand = 'Fortify on Demand',
  fossa = 'Fossa',
  gitleaks = 'Gitleaks',
  grype = 'Grype',
  mend = 'Mend',
  metasploit = 'Metasploit',
  nessus = 'Nessus',
  nexusiq = 'Sonatype Nexus',
  nikto = 'Nikto',
  nmap = 'Nmap',
  odat = 'Odat',
  openvas = 'OpenVAS',
  'osv-scanner' = 'OSV-Scanner',
  owasp = 'OWASP',
  prowler = 'Prowler',
  qualys = 'Qualys',
  reapsaw = 'Reapsaw',
  redlock = 'Redlock',
  scoutsuite = 'ScoutSuite',
  semgrep = 'Semgrep',
  servicenow = 'ServiceNow',
  shiftleft = 'ShiftLeft',
  sniper = 'Sn1per',
  snyk = 'Snyk',
  sonarqube = 'SonarQube',
  sqlmap = 'SQLMap',
  sysdig = 'Sysdig',
  tenableio = 'Tenable.io',
  twistlock = 'Prisma Cloud',
  traceable = 'Traceable',
  veracode = 'Veracode',
  whitesource = 'Mend',
  wiz = 'Wiz',
  xray = 'JFrog Xray',
  zap = 'Zap'
}
